### ISSUE TITLE
How to set readonly but not disable state?

### ISSUE THREAD

**Issue by zalevan** [vaadin/vaadin-checkbox#141]

**Comment by web-padawan** [comment]
Thanks for the question. We generally follow the HTML elements behaviour:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#readonly

> The difference between disabled and readonly is that read-only controls can still function, whereas disabled controls generally do not function as controls until they are enabled.

> Only text controls can be made read-only, since for other controls (such as checkboxes and buttons) there is no useful distinction between being read-only and being disabled, so the readonly attribute does not apply.

So, at this point we are not going to introduce the readonly state for the checkbox.

**Comment by JoeBrig** [comment]
The vaadin-checkbox Java component allows the setReadOnly to be called and it functions as expected. The user is not allowed to modify the value.  This problem is that visually there is no indication that the field is read-only.   

There is a "useful distinction" between read-only and disabled controls, at least in the way Vaadin has implemented disabled and read only. Read only fields show the label with a normal font, disabled fields have the label grayed out.  

The functionally should have the checkbox indicate read-only with a black on white checkbox in a dotted box, as other fields do, and the label should be in normal font and not grayed out.
