### ISSUE TITLE
Material checkbox group: theme variant VERTICAL doesn't work

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-checkbox#158]
the variant adds CSS to the wrong element; it's applied to the root, when it should be applied to vaadin-group-field-container.

**Comment by tomivirkki** [comment]
Which Vaadin version are you using? With 14.0.3 and with the following source:

```java
CheckboxGroup<String> group = new CheckboxGroup<String>();
group.setItems("one", "two", "three");
group.addThemeVariants(CheckboxGroupVariant.LUMO_VERTICAL);
add(group);
```
the result looks ok:
![Screenshot 2019-11-25 11 45 03](https://user-images.githubusercontent.com/1222264/69529559-300f7400-0f79-11ea-8ac3-6200a7ce7031.png)

**Comment by tmattsso** [comment]
14.1.0.beta1

**Comment by tomivirkki** [comment]
Works fine for me on 14.1.0.beta1 and 14.1.0.beta3 with the code above. Please provide some example code that produces the issue.

**Comment by web-padawan** [comment]
It turns out the issue is related to Material theme:

https://github.com/vaadin/vaadin-checkbox/blob/0b3b8e803f6e30c7992d76b0c05be740850e5172/theme/material/vaadin-checkbox-group-styles.html#L38-L41

This has been left without attention for 3 months because of incomplete information. 
Of course it's us who should triage the new issues, but we appreciate proper bug reports.
 
So, I kindly ask you to provide as much information as possible the next time.
