### ISSUE TITLE
Space press doesn’t change the intermediate state (Safari)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox#19]

**Comment by limonte** [comment]
In can reproduce this issue in the UX-test app, but I can't reproduce it locally. Probably it was fixed in the meantime, maybe https://github.com/vaadin/vaadin-checkbox/issues/15 was the reason and it looks like https://github.com/vaadin/vaadin-checkbox/pull/23 fixes this issue also.

Revisit after merging https://github.com/vaadin/vaadin-checkbox/pull/23

**Comment by tomivirkki** [comment]
worksforme also

**Comment by limonte** [comment]
Most probably this is an issue in https://wc.demo.vaadin.com/vaadin-checkbox-ux-test/ Closing for now.
