### ISSUE TITLE
Tabindex doesn't work on Firefox

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox#52]
Try "Checkboxes with Custom Tabindex" demo with Firefox.

Also, there’s both tabindex and tab-index attributes!

**Comment by samiheikki** [comment]
Shadow DOM tabindex works weirdly in FF. It seems to stab Shadow DOM elements tabindex into document’s tabbing sequence.

```
<vaadin-checkbox-group value="{{checkboxValue}}" label="Preferred language of contact:">
  <vaadin-checkbox value="en" tabindex="1">English</vaadin-checkbox>
  <vaadin-checkbox value="fr" tabindex="3">Français</vaadin-checkbox>
  <vaadin-checkbox value="de" tabindex="2">Deutsch</vaadin-checkbox>
</vaadin-checkbox-group>
```

When moving with tab it moves from 1->3->2. When moving back with shift-tab it moves from 3->2->1 (as expected. But also with shift-tab it focuses active link of demo site’s top navigation between “Copy button” and checkbox-group.

Furthermore when adding `tabindex=0` to vaadin-checkbox-group you can’t focus checkboxes anymore (unlike in other browsers).

I also found old Gecko bug related with the issue that hos not been resolved yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1117552

I feel like the issue can’t be fixed in our codebase.

**Comment by web-padawan** [comment]
Works for me in Firefox 67. At least the problems from the above comment seem to be fixed.
The issue was most likely related to polyfilled version.
