### ISSUE TITLE
The "will-change" styles hurt scrolling performance in <vaadin-grid>

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox#58]
This is especially evident with Safari. Open https://cdn.vaadin.com/vaadin-grid/5.0.0-alpha3/demo/#grid-selection-demos and try scrolling the grid in "Multi-Selection Column" demo.

Disabling both `will-change` styles in https://github.com/vaadin/vaadin-checkbox/blob/master/theme/valo/vaadin-checkbox.html fixes the issue.

**Comment by tomivirkki** [comment]
@jouni can something be done in Valo to mitigate this? Fox example having the `will-change` styles effective only on focused.

**Comment by jouni** [comment]
I’m okay if we just remove the `will-change` properties for now. I’ve just added them basically because I think it’s some sort of best practice to let the browser know some things will transition. Not sure if it has any significant *positive* performance implications.

But since it has identified *negative* performance implications, let’s just remove them for now.

**Comment by web-padawan** [comment]
BTW, per [this blog post](https://dev.opera.com/articles/css-will-change-property/#give-the-browser-enough-time-to-work), applying `will-change` for a change that is already taking place (e. g. hover, focused etc) has little effect.

**Comment by tomivirkki** [comment]
In this case it could alleviate some rendering issues. Simply removing `will-change` would result in the following on Safari:
![kapture 2018-01-05 at 11 07 59](https://user-images.githubusercontent.com/1222264/34602620-1e3d51c8-f209-11e7-9c63-06d13a6526d0.gif)

**Comment by jouni** [comment]
Possible workaround: add `-webkit-font-smoothing: antialiased;` for the grid host element.
