### ISSUE TITLE
Focus-ring gets preserved when activating focusable element in label

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-checkbox#62]
## Description

When the label slot contains focusable element (`<a>` might be the most common use case), focus-ring style is still applied to the host element while the focus is in that light DOM element.

![screen shot 2018-01-09 at 16 49 23](https://user-images.githubusercontent.com/10589913/34726837-d122b1c8-f55d-11e7-82be-94ce26d1afda.png)

## Demo

Run [this fiddle](https://jsfiddle.net/webpadawan/ozczbroo/), hit Tab twice and you will see the `focus-ring` style on the checkbox with the native outline on the link at the same time.

**Comment by jouni** [comment]
I don’t know if this specific use case needs to be supported. You could just as well move the link outside the checkbox and the user would not know the difference.

**Comment by web-padawan** [comment]
This is also related to #63 and should be probably fixed in the same PR.

**Comment by Haprog** [comment]
I just want to note here (even though I mention it in #63) that I think this case should be supported because:
1. It is also supported by native checkbox with label combination.
2. If the link is in the middle of text (not the end) then there is no trivial workaround if you want to keep the link clickable an all of the other plain text affecting the checked state.
3. If the link is moved outside the checkbox there is extra space between the elements (so the link seems out of place instead of looking like being part of the same sentence as the label text) unless you add custom CSS.

**Comment by jouni** [comment]
@Haprog, agreed, all very true and good reasons to support links inside the label.

**Comment by web-padawan** [comment]
Can't reproduce this anymore. Was fixed at some point.
