### ISSUE TITLE
publish a change event

### ISSUE THREAD

**Issue by robrez** [vaadin/vaadin-checkbox#81]
Currently, it is only possible to detect changes by observing property changes.  Would like to see a change event that is only fired as a result of user interaction

**Comment by web-padawan** [comment]
Thank you for the issue! Per [this spec](https://html.spec.whatwg.org/multipage/input.html#concept-input-apply), it makes sense to implement the change event for this component.

Aside note: we might want to add a "latency" feature, e. g. in order to prevent this event on miss-click (when the checkbox gets quickly checked and then unchecked back during certain amount of time, e. g. 300 ms).

**Comment by dflorey** [comment]
I'm still experiencing this issue. Are there plans to fix the "checked-changed" event on init?

**Comment by dflorey** [comment]
Sorry for the noise... just found the @change event
